# Generated by Django 4.1 on 2024-01-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="limits",
            field=models.IntegerField(
                choices=[(0, "学生"), (1, "管理员"), (2, "企业")], default=2, verbose_name="权限"
            ),
        ),
    ]
