# Generated by Django 4.1 on 2024-01-20 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0003_enterprise_end_time_enterprise_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enterprise",
            name="end_time",
        ),
    ]
