# Generated by Django 4.1 on 2024-01-20 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_admin_limits"),
        ("enterprise", "0005_enterprise_end_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="major",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.major",
                verbose_name="专业",
            ),
        ),
    ]
