# Generated by Django 4.1 on 2024-01-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0006_enterprise_major"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="limits",
            field=models.IntegerField(
                choices=[(0, "学生"), (1, "管理员"), (2, "企业"), (3, "学校")],
                default=2,
                verbose_name="权限",
            ),
        ),
    ]
