# Generated by Django 4.1 on 2024-02-01 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0010_alter_student_jianli"),
        ("enterprise", "0007_alter_enterprise_limits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enterprise",
            name="jianli",
        ),
        migrations.CreateModel(
            name="StudentEnterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "未查看"), (1, "通过"), (2, "未通过")],
                        default=0,
                        verbose_name="状态",
                    ),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enterprise.enterprise",
                        verbose_name="企业",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.student",
                        verbose_name="学生",
                    ),
                ),
            ],
        ),
    ]
