# Generated by Django 4.1 on 2024-01-21 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_admin_limits"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="学校名称")),
                ("address", models.CharField(max_length=32, verbose_name="学校地址")),
                (
                    "major",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school.major",
                        verbose_name="拥有专业",
                    ),
                ),
            ],
        ),
    ]
