# Generated by Django 4.1 on 2024-01-21 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="major",
        ),
        migrations.AddField(
            model_name="major",
            name="school",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.school",
                verbose_name="所属学校",
            ),
        ),
    ]
