# Generated by Django 4.1 on 2024-01-21 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0005_remove_school_major_major_school"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolMajor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "major",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school.major",
                        verbose_name="专业",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school.school",
                        verbose_name="学校",
                    ),
                ),
            ],
        ),
    ]
