# Generated by Django 4.1 on 2024-01-21 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0006_schoolmajor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="major",
            name="school",
        ),
    ]
