# Generated by Django 4.1 on 2024-01-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0007_remove_major_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="limits",
            field=models.IntegerField(
                choices=[(0, "学生"), (1, "管理员"), (2, "企业"), (3, "学校")],
                default=3,
                verbose_name="权限",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="password",
            field=models.CharField(default="123", max_length=64, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="admin",
            name="limits",
            field=models.IntegerField(
                choices=[(0, "学生"), (1, "管理员"), (2, "企业"), (3, "学校")],
                default=1,
                verbose_name="权限",
            ),
        ),
    ]
