# Generated by Django 4.1 on 2024-01-21 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0008_school_limits_school_password_alter_admin_limits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolmajor",
            name="major",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.major",
                verbose_name="专业",
            ),
        ),
        migrations.AlterField(
            model_name="schoolmajor",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.school",
                verbose_name="学校",
            ),
        ),
    ]
