# Generated by Django 4.1 on 2024-01-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0010_major_school"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="major",
            name="school",
        ),
    ]
