# Generated by Django 4.1 on 2024-01-23 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0007_alter_enterprise_limits"),
        ("school", "0011_remove_major_school"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolEnterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="enterprise.enterprise",
                        verbose_name="企业",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school.school",
                        verbose_name="学校",
                    ),
                ),
            ],
        ),
    ]
