# Generated by Django 4.1 on 2024-01-23 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0007_alter_enterprise_limits"),
        ("school", "0012_schoolenterprise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolenterprise",
            name="enterprise",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enterprise.enterprise",
                verbose_name="企业",
            ),
        ),
        migrations.AlterField(
            model_name="schoolenterprise",
            name="school",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.school",
                verbose_name="学校",
            ),
        ),
    ]
