# Generated by Django 4.1 on 2024-01-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_student_password_alter_student_major"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="limits",
            field=models.IntegerField(
                choices=[(0, "学生"), (1, "管理员"), (2, "企业")], default=0, verbose_name="权限"
            ),
        ),
    ]
