# Generated by Django 4.1 on 2024-01-21 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0007_remove_major_school"),
        ("student", "0006_remove_student_end_time_remove_student_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="school",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="school.school",
                verbose_name="学校",
            ),
        ),
    ]
