# Generated by Django 4.1 on 2024-01-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0009_alter_student_jianli"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="media",
            field=models.FileField(
                blank=True, null=True, upload_to="media/", verbose_name="简历"
            ),
        ),
    ]
